/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprolog;

/**
 *
 * @author Jean
 */
public class FrameJavaProlog extends javax.swing.JFrame {

    /**
     * Creates new form FrameJavaProlog
     */
    public FrameJavaProlog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tab_Panel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descripcion_Area = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Container_principal = new javax.swing.JPanel();
        ReS_Boton = new javax.swing.JButton();
        Mi_Boton = new javax.swing.JButton();
        La_Boton = new javax.swing.JButton();
        Si_Boton = new javax.swing.JButton();
        Instruccion_Label = new javax.swing.JLabel();
        Do_Boton = new javax.swing.JButton();
        Re_Boton = new javax.swing.JButton();
        Sol_Boton = new javax.swing.JButton();
        LaS_Boton = new javax.swing.JButton();
        DoS_Boton = new javax.swing.JButton();
        SolS_Boton = new javax.swing.JButton();
        Fa_Boton = new javax.swing.JButton();
        FaS_Boton = new javax.swing.JButton();
        progresion_TextArea = new javax.swing.JTextField();
        Progresion_Label = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Descripcion_Area.setColumns(20);
        Descripcion_Area.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Descripcion_Area.setRows(5);
        Descripcion_Area.setText("\n\tSistema de composiciòn musical aleatoria.\n\n\nEste programa toma por entrada una nota que usted proporciona al \nhacer clic en el botón que representa la nota deseada y generará como\nsalida un segmento musical en la tonalidad de la nota que se tomó por \nentrada. \n\nPara la generación del segmento musical, primero se identifica cuál fue\nla nota de entrada, una vez identificada, se procede a generar una \nsecuencia de notas que siga la estructura de la Escala Menor Armónica y\nque tenga como nota raíz la nota de entrada. \n\nAsí por ejemplo, si la nota de entrada fue A entonces una secuencia \nválida que el programa generaría sería la siguiente: \n\t           \n\t         A – B – C – D – E – F – G# – A.\n\nElaborado por:\n\tBrandon Alvarez.\n                Jean Carlo Zùñiga.");
        jScrollPane1.setViewportView(Descripcion_Area);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        Tab_Panel.addTab("Acerca de", jPanel2);

        ReS_Boton.setText("D# - RE*");
        ReS_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReS_BotonActionPerformed(evt);
            }
        });

        Mi_Boton.setText("E - MI");
        Mi_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi_BotonActionPerformed(evt);
            }
        });

        La_Boton.setText("A - LA");
        La_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                La_BotonActionPerformed(evt);
            }
        });

        Si_Boton.setText("B - SI");
        Si_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Si_BotonActionPerformed(evt);
            }
        });

        Instruccion_Label.setText("Seleccione la nota musical a reproducir la escala menor armónica.");

        Do_Boton.setText("C - DO");
        Do_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Do_BotonActionPerformed(evt);
            }
        });

        Re_Boton.setText("D - RE");
        Re_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Re_BotonActionPerformed(evt);
            }
        });

        Sol_Boton.setText("G - SOL");
        Sol_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sol_BotonActionPerformed(evt);
            }
        });

        LaS_Boton.setText("A# - LA*");
        LaS_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaS_BotonActionPerformed(evt);
            }
        });

        DoS_Boton.setText("C# - DO*");
        DoS_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoS_BotonActionPerformed(evt);
            }
        });

        SolS_Boton.setText("G# - SOL*");
        SolS_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolS_BotonActionPerformed(evt);
            }
        });

        Fa_Boton.setText("F - FA");
        Fa_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fa_BotonActionPerformed(evt);
            }
        });

        FaS_Boton.setText("F# - FA*");
        FaS_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaS_BotonActionPerformed(evt);
            }
        });

        progresion_TextArea.setText("Aún no se genera progresión.");
        progresion_TextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progresion_TextAreaActionPerformed(evt);
            }
        });

        Progresion_Label.setText("Progresión generada:");

        jButton2.setText("jButton2");

        jButton4.setText("jButton4");

        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 25));

        jButton3.setText("jButton3");

        jButton5.setText("jButton5");
        jButton5.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Container_principalLayout = new javax.swing.GroupLayout(Container_principal);
        Container_principal.setLayout(Container_principalLayout);
        Container_principalLayout.setHorizontalGroup(
            Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Container_principalLayout.createSequentialGroup()
                        .addComponent(Instruccion_Label)
                        .addGap(70, 70, 70))
                    .addGroup(Container_principalLayout.createSequentialGroup()
                        .addGroup(Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Si_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LaS_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Do_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoS_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Re_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReS_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Mi_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fa_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FaS_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sol_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SolS_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(La_Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Container_principalLayout.createSequentialGroup()
                                .addComponent(Progresion_Label)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Container_principalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(218, 218, 218))
                            .addGroup(Container_principalLayout.createSequentialGroup()
                                .addGroup(Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(progresion_TextArea))
                                .addContainerGap(20, Short.MAX_VALUE))))))
        );
        Container_principalLayout.setVerticalGroup(
            Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container_principalLayout.createSequentialGroup()
                .addComponent(Instruccion_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Progresion_Label)
                    .addComponent(Do_Boton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Container_principalLayout.createSequentialGroup()
                        .addComponent(DoS_Boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Re_Boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReS_Boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mi_Boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fa_Boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FaS_Boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sol_Boton))
                    .addComponent(progresion_TextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Container_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Container_principalLayout.createSequentialGroup()
                        .addComponent(SolS_Boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(La_Boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LaS_Boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Si_Boton)
                        .addGap(35, 35, 35))
                    .addGroup(Container_principalLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Container_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Container_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 413, Short.MAX_VALUE))
        );

        Tab_Panel.addTab("Ventana de composiciòn musical", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tab_Panel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tab_Panel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void progresion_TextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progresion_TextAreaActionPerformed

    }//GEN-LAST:event_progresion_TextAreaActionPerformed

    private void Do_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Do_BotonActionPerformed
        progresion_TextArea.setText("Progresion para DO");
    }//GEN-LAST:event_Do_BotonActionPerformed

    private void DoS_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoS_BotonActionPerformed
        progresion_TextArea.setText("Progresion para DO sostenido");
    }//GEN-LAST:event_DoS_BotonActionPerformed

    private void Re_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Re_BotonActionPerformed
        progresion_TextArea.setText("Progresion para RE");
    }//GEN-LAST:event_Re_BotonActionPerformed

    private void ReS_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReS_BotonActionPerformed
        progresion_TextArea.setText("Progresion para RE sostenido");
    }//GEN-LAST:event_ReS_BotonActionPerformed

    private void Mi_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi_BotonActionPerformed
        progresion_TextArea.setText("Progresion para MI");
    }//GEN-LAST:event_Mi_BotonActionPerformed

    private void Fa_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fa_BotonActionPerformed
        progresion_TextArea.setText("Progresion para FA");
    }//GEN-LAST:event_Fa_BotonActionPerformed

    private void FaS_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaS_BotonActionPerformed
        progresion_TextArea.setText("Progresion para FA sostenido");
    }//GEN-LAST:event_FaS_BotonActionPerformed

    private void Sol_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sol_BotonActionPerformed
        progresion_TextArea.setText("Progresion para SOL");
    }//GEN-LAST:event_Sol_BotonActionPerformed

    private void SolS_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolS_BotonActionPerformed
        progresion_TextArea.setText("Progresion para SOL sostenido");
    }//GEN-LAST:event_SolS_BotonActionPerformed

    private void La_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_La_BotonActionPerformed
        progresion_TextArea.setText("Progresion para LA");
    }//GEN-LAST:event_La_BotonActionPerformed

    private void LaS_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaS_BotonActionPerformed
        progresion_TextArea.setText("Progresion para LA sostenido");
    }//GEN-LAST:event_LaS_BotonActionPerformed

    private void Si_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Si_BotonActionPerformed
        progresion_TextArea.setText("Progresion para SI");
    }//GEN-LAST:event_Si_BotonActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJavaProlog().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container_principal;
    private javax.swing.JTextArea Descripcion_Area;
    private javax.swing.JButton DoS_Boton;
    private javax.swing.JButton Do_Boton;
    private javax.swing.JButton FaS_Boton;
    private javax.swing.JButton Fa_Boton;
    private javax.swing.JLabel Instruccion_Label;
    private javax.swing.JButton LaS_Boton;
    private javax.swing.JButton La_Boton;
    private javax.swing.JButton Mi_Boton;
    private javax.swing.JLabel Progresion_Label;
    private javax.swing.JButton ReS_Boton;
    private javax.swing.JButton Re_Boton;
    private javax.swing.JButton Si_Boton;
    private javax.swing.JButton SolS_Boton;
    private javax.swing.JButton Sol_Boton;
    private javax.swing.JTabbedPane Tab_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField progresion_TextArea;
    // End of variables declaration//GEN-END:variables
}
